<?php
// $Id$
/**
 * @file buildmode.module
 * Build mode implements common sense themes and formatters for CCK build modes.
 */

/**
 * Implementation of hook_menu().
 */
function buildmode_menu() {
  $items['node/%node/buildmode'] = array(
    'title' => 'Build modes',
    'page callback' => 'buildmode_page_view',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_LOCAL_TASK,
  );
  $count = 0;
  foreach (_buildmode() as $mode => $value) {
    $items['node/%node/buildmode/'. $mode] = array(
      'title' => $value['title'],
      'type' => $count === 0 ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK,
      'page callback' => 'buildmode_page_view',
      'page arguments' => array(1, 3),
      'access callback' => 'node_access',
      'access arguments' => array('view', 1),
    );
    $count++;
  }

  return $items;
}

/**
 * Menu callback; view a single node.
 */
function buildmode_page_view($node, $build_mode = NODE_BUILD_NORMAL) {
  $modes = _buildmode();
  drupal_set_title($modes[$build_mode]['title']);
  return buildmode_node_view($node, $build_mode);
}

/**
 * Generate a display of the given node.
 *
 * @param $node
 *   A node array or node object.
 * @param $build_mode
 *   The build mode name.
 * @param $links
 *   Whether or not to display node links. Links are omitted for node previews.
 *
 * @return
 *   An HTML representation of the themed node.
 *
 * @see node_view()
 */
function buildmode_node_view($node, $build_mode = NODE_BUILD_NORMAL, $links = TRUE) {
  $node = (object)$node;

  // Default arguments from node_view() are passed explicitly because some
  // hook implementations may not set them as defaults.
  $teaser = FALSE;
  $page = FALSE;

  $node->build_mode = $build_mode;

  $node = node_build_content($node, $teaser, $page);

  if ($links) {
    $node->links = module_invoke_all('link', 'node', $node, $teaser);
    drupal_alter('link', $node->links, $node);
  }

  // Teasers don't exist for build modes, but the teaser text might be useful.
  // TODO: Figure out how to safely offer teaser version of body.
  $content = drupal_render($node->content);
  $node->body = $content;
  unset($node->teaser);

  // Allow modules to modify the fully-built node.
  node_invoke_nodeapi($node, 'alter', $teaser, $page);

  return theme('node', $node, $teaser, $page);
}

/**
 * Implementation of hook_theme().
 */
function buildmode_theme($existing, $type, $theme, $path) {
  $modes = _buildmode();
  $info = array();
  foreach ($modes as $mode => $value) {
    $info['buildmode_formatter_buildmode_'. $mode] = array(
      'arguments' => array('element'),
      'function' => 'theme_buildmode_formatter',
    );
  }
  return $info;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function buildmode_field_formatter_info() {
  $modes = _buildmode();
  $info = array();
  foreach ($modes as $mode => $value) {
    $info['buildmode_'. $mode] = array(
      'label' => $value['title'] .' build mode',
      'field types' => array('nodereference'),
      'multiple values' => CONTENT_HANDLE_CORE,
    );
  }
  return $info;
}

/**
 * Override or insert variables into the node templates.
 */
function buildmode_preprocess_node(&$vars, $hook) {
  $modes = _buildmode();
  $node = $vars['node'];
  // Create the build_mode variable.
  if (in_array($node->build_mode, array_keys($modes), TRUE)) {
    $mode = $node->build_mode;
    $vars['build_mode'] = $mode;

    $vars['classes'] .= $vars['classes'] ? ' '. $mode : $mode;

    $vars['template_files'][] = $mode;
    $vars['template_files'][] = $mode .'-'. $node->type;
  }
}

/**
 * Proxy theme function for 'full' and 'teaser' nodereference field formatters.
 */
function theme_buildmode_formatter($element) {
  static $recursion_queue = array();
  $output = '';
  if (!empty($element['#item']['safe']['nid'])) {
    $nid = $element['#item']['safe']['nid'];
    $node = $element['#node'];
    $field = content_fields($element['#field_name'], $element['#type_name']);
    // If no 'referencing node' is set, we are starting a new 'reference thread'
    if (!isset($node->referencing_node)) {
      $recursion_queue = array();
    }
    $recursion_queue[] = $node->nid;
    if (in_array($nid, $recursion_queue)) {
      // Prevent infinite recursion caused by reference cycles:
      // if the node has already been rendered earlier in this 'thread',
      // we fall back to 'default' (node title) formatter.
      return theme('nodereference_formatter_default', $element);
    }
    if ($referenced_node = node_load($nid)) {
      $referenced_node->build_mode = str_replace('buildmode_', '', $element['#formatter']);
      $referenced_node->referencing_node = $node;
      $referenced_node->referencing_field = $field;
      $output = node_view($referenced_node);
    }
  }
  return $output;
}

/**
 * Helper function to return array of all non-core build modes.
 */
function _buildmode() {
  $modes = content_build_modes();
  foreach (array(NODE_BUILD_NORMAL, 'full', 'teaser', NODE_BUILD_PREVIEW, NODE_BUILD_SEARCH_INDEX, NODE_BUILD_SEARCH_RESULT, NODE_BUILD_RSS, NODE_BUILD_PRINT) as $mode) {
    unset($modes[$mode]);
  }
  return $modes;
}
